language: python
python:
  - "2.7"
  #- "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - nosetests code/* --with-coverage
  - flake8 --max-line-length=110 code

after_success:
  - coveralls